#!/bin/bash

# Add below all the subnets (only class C networks)
networkList="1,2,3,4" 

read -p 'Enter last byte : ' octet

IFS=',' read -ra network <<< "$networkList"
for x in "${network[@]}"; do

fping -a 192.168.$x.$octet 2> /dev/null

done
